[package]
name = "spirit_fingers_simhash"
version = "0.4.1"
authors = []
edition = "2021"

[lib]
name = "spirit_fingers_simhash"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.37", default-features = true }
siphasher = "0.3"
