[package]
name = "simhash"
version = "0.2.0"
authors = []
edition = "2018"

[lib]
name = "simhash"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"

[dependencies.simhash]
git = "https://github.com/holsee/simhash-rs.git"
